; ============================================================================
; Nyaa Chat 무설치 초경량 네이티브 클라이언트 환경설정 (settings.ini)
; ============================================================================

[General]
Language=ko

[Server]
Url=https://nemulo.duckdns.org
DefaultChannel=#자유대화
AutoConnect=true
ExtraServers=https://tnemu.duckdns.org
AutoConnectServers=https://nemulo.duckdns.org, https://tnemu.duckdns.org

[AutoJoin]
tnemu.duckdns.org=#자유채널, #바보, #천천히
nemulo.duckdns.org=#자유채널, #바보

[User]
DefaultNickname=로리콘
Avatar=🐾
AgreeTerms=true
QuitMessage=NyaaChat Native - 좋은 하루 되세요!
UserId=u_dfa164ca1

[Window]
Title=Nyaa Chat Native Multi-Server Client
Width=1183
Height=716
AlwaysOnTop=false
Opacity=100
MinimizeToTrayOnClose=false
LeftPanelWidth=240
RightPanelWidth=200

[Theme]
ActiveTheme=default_dark.ini
FontFamily=맑은 고딕
FontSize=10
ShowTimestamps=true
FontWeight=normal

[Logging]
SaveLogs=true

[Sounds]
EnableSounds=true
UseSystemBeepFallback=false
SoundMention=
SoundMessage=
SoundJoin=
SoundAlert=

[Security]
SkipLinkWarning=false
